=== dutradda/OpenAPI-Specification-2.1/schema.json
{
  "title": "An Unofficial JSON Schema for Swagger 2.1 API.",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "required": [
    "swagger",
    "info",
    "paths"
  ],
  "additionalProperties": false,
  "patternProperties": {
    "^x-": {
      "$ref": "schemaDefinitions/definitions.json#/vendorExtension"
    }
  },
  "properties": {
    "swagger": {
      "type": "string",
      "enum": [
        "2.0", "2.1"
      ],
      "description": "The Swagger version of this document."
    },
    "info": {
      "$ref": "schemaDefinitions/definitions.json#/info"
    },
    "host": {
      "type": "string",
      "pattern": "^[^{}/ :\\\\]+(?::\\d+)?$",
      "description": "The host (name or ip) of the API. Example: 'swagger.io'"
    },
    "basePath": {
      "type": "string",
      "pattern": "^/",
      "description": "The base path to the API. Example: '/api'."
    },
    "schemes": {
      "$ref": "schemaDefinitions/definitions.json#/schemesList"
    },
    "consumes": {
      "description": "A list of MIME types accepted by the API.",
      "allOf": [
        {
          "$ref": "schemaDefinitions/definitions.json#/mediaTypeList"
        }
      ]
    },
    "produces": {
      "description": "A list of MIME types the API can produce.",
      "allOf": [
        {
          "$ref": "schemaDefinitions/definitions.json#/mediaTypeList"
        }
      ]
    },
    "parameters": {
      "$ref": "schemaDefinitions/definitions.json#/parametersList"
    },
    "paths": {
      "$ref": "schemaDefinitions/definitions.json#/paths"
    },
    "definitions": {
      "$ref": "schemaDefinitions/definitions.json#/definitions"
    },
    "responses": {
      "$ref": "schemaDefinitions/responsesDefinition.json#"
    },
    "security": {
      "$ref": "schemaDefinitions/securityDefinitions.json#/security"
    },
    "securityDefinitions": {
      "$ref": "schemaDefinitions/securityDefinitions.json#/securityDefinitions"
    },
    "tags": {
      "type": "array",
      "items": {
        "$ref": "schemaDefinitions/definitions.json#/tag"
      },
      "uniqueItems": true
    },
    "externalDocs": {
      "$ref": "schemaDefinitions/definitions.json#/externalDocs"
    }
  }
}

=== dutradda/OpenAPI-Specification-2.1/example/swagger.json
{
    "swagger":"2.1",
    "info":{
        "version": "0.0.1",
        "title": "Store Example"
    },
    "paths": {
        "allOf": [{
            "$ref": "dresses/swagger.json"
        },{
            "$ref": "shoes/swagger.json"
        }]
    },
    "definitions": {
        "allOf": [{
            "$ref": "definitions.json"
        },{
            "$ref": "dresses/definitions.json"
        },{
            "$ref": "shoes/definitions.json"
        }]
    }
}
